ic| headings_mapper: {'activation_date': 'delivery_date',
                      'additional_discount': 'discount',
                      'bill_to': 'bill_to',
                      'customer_id': 'customer_id',
                      'distributor_discount': 'distributor_discount',
                      'distributor_id': 'distributor_id',
                      'invoice_date': 'invoice_date',
                      'invoice_number': 'invoice_number',
                      'invoice_status': 'invoice_status',
                      'order_cnf_date': 'requested_date',
                      'payment_status': 'payment_status',
                      'payment_terms': 'payment_terms',
                      'per_unit_price': 'unit_price',
                      'product_id': 'product_id',
                      'product_rebate_type': 'distributor_type',
                      'purchase_type': 'purchase_type',
                      'quantity': 'quantity',
                      'renewal_type': 'renewal_type',
                      'shipping_method': 'shipping_method',
                      'vendor_commision': 'vendor_commision'}
ic| converted_data[0]: {'activation_date': datetime.datetime(2023, 3, 2, 0, 0),
                        'additional_discount': 0.0,
                        'bill_to': 'THINKSYNQ SOLUTIONS PRIVATE LIMITED',
                        'customer_id': 'CUST-T-2026-100037',
                        'distributor_discount': 0.15,
                        'distributor_id': 'DIST-T-2026-100006',
                        'invoice_date': Timestamp('2023-03-03 00:00:00'),
                        'invoice_number': 'TBS2223IN131',
                        'invoice_status': 'COMPLETED',
                        'order_cnf_date': datetime.datetime(2023, 3, 2, 0, 0),
                        'payment_status': 'PAID',
                        'per_unit_price': 1290.0,
                        'product_id': 'PROD-T-2026-100459',
                        'product_rebate_type': 'REBATE',
                        'purchase_type': 'EXISTING-RENEWAL',
                        'quantity': 120,
                        'renewal_type': 'YEARLY-BILL',
                        'shipping_method': 'ONLINE',
                        'vendor_commision': '0%'}
ic| len(converted_data[0]): 19, len(headings_mapper): 20