from enum import Enum


class CustomerIndustries(Enum):
    AGRICULTURE = "Agriculture"
    AUTOMOTIVE = "Automotive"
    AVIATION = "Aviation & Aerospace"
    BANKING = "Banking"
    BIOTECHNOLOGY = "Biotechnology"
    CHEMICALS = "Chemicals"
    CONSTRUCTION = "Construction"
    CONSUMER_GOODS = "Consumer Goods"
    DEFENSE = "Defense"
    EDUCATION = "Education"
    ENERGY = "Energy"
    ENGINEERING = "Engineering"
    ENTERTAINMENT = "Entertainment & Media"
    ENVIRONMENTAL = "Environmental Services"
    FINANCIAL_SERVICES = "Financial Services"
    FOOD_BEVERAGE = "Food & Beverage"
    GOVERNMENT = "Government"
    HEALTHCARE = "Healthcare"
    HOSPITALITY = "Hospitality"
    INSURANCE = "Insurance"
    IT_SERVICES = "IT Services"
    LEGAL = "Legal Services"
    LOGISTICS = "Logistics & Supply Chain"
    MANUFACTURING = "Manufacturing"
    MARKETING = "Marketing & Advertising"
    MINING = "Mining"
    NON_PROFIT = "Non-Profit"
    PHARMACEUTICALS = "Pharmaceuticals"
    PROFESSIONAL_SERVICES = "Professional Services"
    REAL_ESTATE = "Real Estate"
    RETAIL = "Retail"
    TELECOMMUNICATIONS = "Telecommunications"
    TEXTILES = "Textiles & Apparel"
    TOURISM = "Tourism & Travel"
    TRANSPORTATION = "Transportation"
    UTILITIES = "Utilities"
    WHOLESALE = "Wholesale"
    SOFTWARE = "Software & SaaS"
    ECOMMERCE = "E-Commerce"
    CYBERSECURITY = "Cybersecurity"
    DATA_ANALYTICS = "Data & Analytics"
    ARTIFICIAL_INTELLIGENCE = "Artificial Intelligence"
    BLOCKCHAIN = "Blockchain & Web3"
    IOT = "Internet of Things (IoT)"
    GAMING = "Gaming"
    SPORTS = "Sports"
    FASHION = "Fashion"
    MARITIME = "Maritime"
    SPACE = "Space Technology"
    OTHER = "Other"

class CustomerSectors(Enum):
    PRIVATE="private".upper()
    PUBLIC='public'.upper()