from enum import Enum


class PaymentTermsEnum(Enum):
    SEVEEN_DAYS="7-DAYS"
    FIFTEN_DAYS="15-DAYS"
    THIRTY_DAYS="30-DAYS"


class PaymentStatus(Enum):
    PAID ='paid'.upper()
    NOT_PAID = "not paid".upper()
    TDS_PENDING="TDS PENDING"
    FULL_PAYMENT_RECEIVED="FULL PAYMENT RECEIVED"
    HALF_PAYMENT_RECEIVED="HALF PAYMENT RECEIVED"
    SHORT_PAYMENT_RECEIVED="SHORT PAYMENT RECEIVED"
    GST_PENDING="GST PENDING"


class InvoiceStatus(Enum):
    COMPLETED='completed'.upper()
    INCOMPLETED='incompleted'.upper()

class BillingType(Enum):
    SUBSCRIPTION = "SUBSCRIPTION"
    ONE_TIME = "ONE_TIME"

class ShippingMethods(Enum):
    ONLINE ='online'.upper()
    OFFLINE ='offline'.upper()


class RenewalTypes(Enum):
    YEARLY_BILL="YEARLY-BILL"
    MONTHLY_BILL="MONTHLY-BILL"
    HALFLY_BILL='HALFLY-BILL'
    YEARLY_YEARLY_BILL="YEARLY-YEARLY-BILL"
    MONTHLY_ANNUAL_COMMITMENT="MONTHLY-ANNUAL-COMMITMENT"
    MONTHLY_BILL_MONTHLY_COMMITMENT="MONTHLY-BILL-MONTHLY-COMMITMENT"
    QUARTELY_BILL_ANNUAL_COMMITMENT="QUARTELY-BILL-ANNUAL-COMMITMENT"
    HALFLY_BILL_ANNUAL_COMMITMENT="HALFLY-BILL-ANNUAL-COMMITMENT"

class PurchaseTypes(Enum):
    NEW_LOGO_RENEWAL="NEW-LOGO-RENEWAL"
    NET_NEW_CUSTOMER="NET-NEW-CUSTOMER"
    EXISTING_RENEWAL="EXISTING-RENEWAL"
    EXISTING_ADD_ON="EXISTING-ADD-ON"

class DistributorType(Enum):
    REBATE="REBATE"
    NON_REBATE="NON-REBATE"